[package]
name = "mock-anchor"
version = "0.1.0"
authors = ["larry0x <larry@delphidigital.io>"]
edition = "2018"
exclude = ["contract.wasm", "hash.txt"]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
# The Anchor team have not pushed v1.0.0 to crates.io, so we have to import using GitHub URL
anchor-token = { version = "1.0.0", git = "https://github.com/Anchor-Protocol/anchor-token-contracts" }
cosmwasm-bignumber = "1.0"
cosmwasm-std = { version = "0.10.1", features = ["iterator"] }
cosmwasm-storage = { version = "0.10.1", features = ["iterator"] }
cw20 = "0.2"
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = "0.13.2"