[package]
name = "fields-of-mars"
version = "0.1.0"
authors = ["larry0x <larry@delphidigital.io>"]
edition = "2018"

[dependencies]
cosmwasm-std = "0.10.1"
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
