[package]
name = "fields-of-mars"
version = "0.5.0"
authors = ["larry_0x <larry@delphidigital.io>"]
edition = "2018"
license = "UNLICENSED"
repository = "https://github.com/mars-protocol/field-of-mars"

[dependencies]
anchor-token = "0.2.0"
astroport = { path = "../astroport" }
mars = { path = "../mars_core" }
red-bank = { path = "../red_bank" } 
mars-periphery = { path = "../mars_periphery" }
mirror-protocol = "2.1.1"

cosmwasm-std = "0.16.0"
cw20 = "0.8.0"

cosmwasm-bignumber = "2.2.0"
terra-cosmwasm = "2.2.0"

schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }