[package]
name = "field-of-mars"
version = "0.1.0"
authors = ["larry0x <larry@delphidigital.io>"]
edition = "2018"

[dependencies]
cosmwasm-std = "0.10.1"
cw20 = "0.2"
mars = { path = "../../packages/mars" }
mirror-protocol = { path = "../../packages/mirror" }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
terraswap = "1.2.0"
